### ISSUE TITLE
Error while starting RbTray *in windows 11* Couldn't register hotkey

### ISSUE THREAD

**Issue by kartikfire** [benbuck/rbtray#62]
When i try to start rbtray in windows 11 i get this error (the program still works, but the hotkey does not),
i just upgraded to [windows 11](https://www.microsoft.com/en-us/windows/windows-11), im not sure if this issue is with rbtray or windows 11...
![image](https://user-images.githubusercontent.com/71930656/124253897-8a9b8980-db39-11eb-8fc8-ee17cc7270dd.png)

**Comment by benbuck** [comment]
Hi @kartikfire,

Oh no, that's unfortunate. I don't have Windows 11 yet, but I'm guessing it means that Microsoft started using the same Windows-Alt-Down keyboard shortcut for something. I can't seem to find out what by searching for it, do you have any ideas?

Thanks,
Benbuck

**Comment by kartikfire** [comment]
Yes, windows + alt + arrow key's. Changes the position of a window, the change is static.

**Comment by benbuck** [comment]
Hi @kartikfire,

Thanks for verifying that. It means that to be compatible with Windows 11, RBTray will need to change the hotkey it uses to something else that Windows isn't using.

-Benbuck

**Comment by aadikudo** [comment]
Hey, I also upgraded to Windows 11, and Win-Alt-Down button is now being used to change folder orientation. This particular hotkey was added in version 4.7. So for a quick fix, download version 4.6 until there is an alternate for this.

**Comment by kartikfire** [comment]
Can there be a feature that allows us to change hotkey? if there is then it would probably fix the issue and users can change the hotkey to what they like.

**Comment by benbuck** [comment]
@aadikudo: thanks for the suggested temporary workaround.

@kartikfire: that's a reasonable suggestion, let me think about a good way to do that.

Thanks,
Ben

**Comment by eladkarako** [comment]
<details><summary>I can test it using a recent W11 preview, no problem</summary>  

Windows 11 can be downloaded using https://uupdump.net/ from MS servers (that's a preview copy but you may activate it).  
B.T.W. I'm currently using a very recent preview of Windows 10 `19044.1200.210812-1726.21H2_RELEASE_SVC_PROD3_CLIENTMULTI_X64FRE_EN-US` which works fine.
</details>

maybe that's a small fix,  

<details><summary>I have noticed that the exe/dlls are missing the compatibility part in the manifest,  
which means the application runs in a vista-virtualization compatibility mode.</summary>  

![2021-09-06_141549](https://user-images.githubusercontent.com/415238/132209373-31fc80e1-0f09-4c4e-b490-bbdde824f814.jpg)  

![2021-09-06_141612](https://user-images.githubusercontent.com/415238/132209388-dbf3c05f-fd34-40c5-960b-95455c8898b3.jpg)

```xml
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> <!-- without it, apps will run in windows vista compatibility in windows 7.   https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#compatibility --> 
    <application> 
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"></supportedOS> <!-- Windows 10/11  /  Windows Server 2016/2019  --> 
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"></supportedOS> <!-- Windows 8.1    /  Windows Server 2012 R2    --> 
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"></supportedOS> <!-- Windows 8      /  Windows Server 2012       --> 
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"></supportedOS> <!-- Windows 7      /  Windows Server 2008 R2    --> 
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"></supportedOS> <!-- Windows Vista  /  Windows Server 2008       --> 
    </application> 
  </compatibility> 
```

</details>

can you try this patched exe/dll files of v4.11,  
<details><summary>using a modified manifest</summary>

that's just <a href="https://github.com/eladkarako/manifest">a generic one</a> I use in my projects  
to test stuff before I rebuild.  
as a program w/o UI it does not needs the settings part really, nor the common controls part.  
but I just drag/drop it to quickly patch it for testing purposes.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<!-- August 2021. Elad Karako. --> 
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0"> 
<!-- a segment for identity, optional (you don't need it, unless you know you need it). --> 
<!-- 
  <assemblyIdentity 
      name="Microsoft.Windows.Shell.calc" 
      processorArchitecture="x86" 
      version="5.1.0.0" 
      type="win32"/> 
  <description>Windows Calc</description> 
--> 
<!-- apply the current Windows-theme to the controls of the application, if possible. --> 
  <dependency> 
    <dependentAssembly> 
      <assemblyIdentity name="Microsoft.Windows.Common-Controls" 
        version="6.0.0.0" publicKeyToken="6595b64144ccf1df" 
        type="win32" processorArchitecture="*" language="*"></assemblyIdentity> 
    </dependentAssembly> 
  </dependency> 
  <application xmlns="urn:schemas-microsoft-com:asm.v3"> 
     <windowsSettings>  <dpiAware                           xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>                        </windowsSettings>     <!-- https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#dpiaware --> 
<!-- <windowsSettings>  <printerDriverIsolation             xmlns="http://schemas.microsoft.com/SMI/2011/WindowsSettings">true</printerDriverIsolation>             </windowsSettings> --> <!-- for apps that initiate printing (such as Chrome, MS-word, Paint.Net), calls printer driver from within a sandbox so if it crashes it does not really effects the app itself or the OS, not really needed. unspecified value tend to work fine in either classic or shared manner (shared is default win W7+).  https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#printerdriverisolation --> 
<!-- <windowsSettings>  <highResolutionScrollingAware       xmlns="http://schemas.microsoft.com/SMI/2011/WindowsSettings">true</highResolutionScrollingAware>       </windowsSettings> --> <!-- ** DO NOT USE!!!!!! **  crashes apps in W10! should increase resolution in mouses that supports high DPI (1200 and such) but even putting it in the manifest - regardless of value WILL CRASH THE APP in W10+!!!  manually look in entries in: https://docs.microsoft.com/en-us/windows/win32/sbscs/manifest-file-schema#code-try-0 --> 
<!-- <windowsSettings>  <ultraHighResolutionScrollingAware  xmlns="http://schemas.microsoft.com/SMI/2011/WindowsSettings">true</ultraHighResolutionScrollingAware>  </windowsSettings> --> <!-- ** DO NOT USE!!!!!! **  crashes apps in W10! should increase resolution in mouses that supports (very) high DPI (1200 and such) but even putting it in the manifest - regardless of value WILL CRASH THE APP in W10+!!!  manually look in entries in: https://docs.microsoft.com/en-us/windows/win32/sbscs/manifest-file-schema#code-try-0 --> 
     <windowsSettings>  <dpiAwareness                       xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2,PerMonitor</dpiAwareness>    </windowsSettings>     <!-- improve 'dpiAware', can specify both. should help scale up legacy apps. https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#dpiawareness --> 
     <windowsSettings>  <longPathAware                      xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>                      </windowsSettings>     <!-- windows 10 only, override MAX_PATH (260) character limit in various windows APIs to allow 32k characters, paths are getting weird, although it is handled by the windows API so legacy apps should be fine too.   also requires registry editing since this feature is disabled in the OS by default. not a good idea to turn this ON since you might take files in sd-card or portable HD elsewhere and won't be able to copy or read stuff.   https://docs.microsoft.com/en-gb/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later  --> 
<!-- <windowsSettings>  <gdiScaling                         xmlns="http://schemas.microsoft.com/SMI/2017/WindowsSettings">true</gdiScaling>                         </windowsSettings> --> <!-- makes graphic programs such as ones that takes screenshots have bad functionality with larger-DPI (ease of access), since it also enlarges the controls in sub containers, and somtimes breaks the UI, for non-graphic-programs it might improve scale text and standard controls in apps, prevents blur. useful if you are using non 100% DPI for example in 'ease-of-access'. https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#gdiscaling --> 
<!-- <windowsSettings>  <activeCodePage                     xmlns="http://schemas.microsoft.com/SMI/2019/WindowsSettings">UTF-8</activeCodePage>                    </windowsSettings> --> <!-- changes a legacy program from default Windows code page 1252 to UTF-8, might mess-up display.     https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#activecodepage   https://docs.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page#code-try-1   --> 
     <windowsSettings>  <heapType                           xmlns="http://schemas.microsoft.com/SMI/2020/WindowsSettings">SegmentHeap</heapType>                    </windowsSettings>     <!-- change windows heap API to use a modern implementation, windows 10+ only.                         https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#heaptype                                                                                                          --> 
  </application> 
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"> 
    <security> 
      <requestedPrivileges> 
        <requestedExecutionLevel level="asInvoker"            uiAccess="false" /> 
   <!-- <requestedExecutionLevel level="highestAvailable"     uiAccess="false" /> --> <!-- best to avoid! use either 'asInvoker' or 'requireAdministrator'.  if you want to use this one - essentially the cases are bi-functional application, use if program can manage most of its functionality (such read only protected files/registry) but can work in write mode when user has admin right, dialog for admin details will be shown on demans, and if not providing admin-auth the specific action fails but the app can still run. --> 
   <!-- <requestedExecutionLevel level="requireAdministrator" uiAccess="false" /> --> <!-- use if program requires admin-access. standard user gets credentials dialog for admin-account-details. won't start the app without some admin-auth-details. --> 
      </requestedPrivileges> 
    </security> 
  </trustInfo> 
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> <!-- without it, apps will run in windows vista compatibility in windows 7.   https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#compatibility --> 
    <application> 
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"></supportedOS> <!-- Windows 10/11  /  Windows Server 2016/2019  --> 
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"></supportedOS> <!-- Windows 8.1    /  Windows Server 2012 R2    --> 
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"></supportedOS> <!-- Windows 8      /  Windows Server 2012       --> 
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"></supportedOS> <!-- Windows 7      /  Windows Server 2008 R2    --> 
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"></supportedOS> <!-- Windows Vista  /  Windows Server 2008       --> 
    </application> 
  </compatibility> 
</assembly> 
 
```
</details>

[x64_manifest_patched.zip](https://github.com/benbuck/rbtray/files/7115608/x64_manifest_patched.zip)  

[x86_manifest_patched.zip](https://github.com/benbuck/rbtray/files/7115614/x86_manifest_patched.zip)

**Comment by sirloinofbeef** [comment]
Following for progress

**Comment by sydbarrett74** [comment]
Confirming that this happens on WIndows 11 general availability release (10.0.22000.194).

**Comment by fragtion** [comment]
I just switched to this version of RBtray (was using the old sourceforge one, 4.3 I think) as I couldn't minimize WhatsApp Desktop to tray.  Suddenly seeing the same error, so it must be specific to this fork ? I'm on Windows 11. Waiting for a fix too

**Comment by fragtion** [comment]
I've created a temporary fork, which modifies only the hotkey, replacing ALT with CTRL. So hotkey is CTRL+WIN+DOWNARROW. It's working great for me, with no error on launch. Feel free to use it until this repo gets updated with a fix:
https://github.com/fragtion/rbtray/releases/tag/v4.11

**Comment by sirloinofbeef** [comment]
>Could someone please run this utility on Windows 11 and provide the list of hotkeys in use from that?

What utility?

**Comment by benbuck** [comment]
Hi @sirloinofbeef,

I forgot to paste the link, here it is:

http://www.nirsoft.net/utils/hot_keys_list.html

-Benbuck

**Comment by sirloinofbeef** [comment]
Hot Key	Alt	Ctrl	Shift	Windows Key	Key	
Alt+Ctrl+Delete	*	*			Delete	
Alt+Ctrl+F11	*	*			F11	
Alt+Ctrl+F12	*	*			F12	
Alt+Ctrl+F8	*	*			F8	
Alt+Ctrl+Shift+Windows Key+D	*	*	*	*	D	
Alt+Ctrl+Shift+Windows Key+L	*	*	*	*	L	
Alt+Ctrl+Shift+Windows Key+N	*	*	*	*	N	
Alt+Ctrl+Shift+Windows Key+O	*	*	*	*	O	
Alt+Ctrl+Shift+Windows Key+P	*	*	*	*	P	
Alt+Ctrl+Shift+Windows Key+Space	*	*	*	*	Space	
Alt+Ctrl+Shift+Windows Key+T	*	*	*	*	T	
Alt+Ctrl+Shift+Windows Key+W	*	*	*	*	W	
Alt+Ctrl+Shift+Windows Key+X	*	*	*	*	X	
Alt+Ctrl+Shift+Windows Key+Y	*	*	*	*	Y	
Alt+F4	*				F4	
Alt+Print Screen	*				Print Screen	
Alt+Shift+Windows Key+F21	*		*	*	F21	
Alt+Windows Key+0	*			*	0	
Alt+Windows Key+1	*			*	1	
Alt+Windows Key+2	*			*	2	
Alt+Windows Key+3	*			*	3	
Alt+Windows Key+4	*			*	4	
Alt+Windows Key+5	*			*	5	
Alt+Windows Key+6	*			*	6	
Alt+Windows Key+7	*			*	7	
Alt+Windows Key+8	*			*	8	
Alt+Windows Key+9	*			*	9	
Alt+Windows Key+B	*			*	B	
Alt+Windows Key+D	*			*	D	
Alt+Windows Key+Down	*			*	Down	
Alt+Windows Key+F	*			*	F	
Alt+Windows Key+F23	*			*	F23	
Alt+Windows Key+G	*			*	G	
Alt+Windows Key+Left	*			*	Left	
Alt+Windows Key+M	*			*	M	
Alt+Windows Key+Print Screen	*			*	Print Screen	
Alt+Windows Key+R	*			*	R	
Alt+Windows Key+Right	*			*	Right	
Alt+Windows Key+T	*			*	T	
Alt+Windows Key+Up	*			*	Up	
Alt+Windows Key+W	*			*	W	
Alt+Windows Key+Y	*			*	Y	
Ctrl+Shift+Windows Key+0		*	*	*	0	
Ctrl+Shift+Windows Key+1		*	*	*	1	
Ctrl+Shift+Windows Key+2		*	*	*	2	
Ctrl+Shift+Windows Key+3		*	*	*	3	
Ctrl+Shift+Windows Key+4		*	*	*	4	
Ctrl+Shift+Windows Key+5		*	*	*	5	
Ctrl+Shift+Windows Key+6		*	*	*	6	
Ctrl+Shift+Windows Key+7		*	*	*	7	
Ctrl+Shift+Windows Key+8		*	*	*	8	
Ctrl+Shift+Windows Key+9		*	*	*	9	
Ctrl+Shift+Windows Key+B		*	*	*	B	
Ctrl+Shift+Windows Key+F21		*	*	*	F21	
Ctrl+Shift+Windows Key+F22		*	*	*	F22	
Ctrl+Shift+Windows Key+F24		*	*	*	F24	
Ctrl+Shift+Windows Key+L		*	*	*	L	
Ctrl+Shift+Windows Key+Space		*	*	*	Space	
Ctrl+Windows Key+0		*		*	0	
Ctrl+Windows Key+1		*		*	1	
Ctrl+Windows Key+2		*		*	2	
Ctrl+Windows Key+3		*		*	3	
Ctrl+Windows Key+4		*		*	4	
Ctrl+Windows Key+5		*		*	5	
Ctrl+Windows Key+6		*		*	6	
Ctrl+Windows Key+7		*		*	7	
Ctrl+Windows Key+8		*		*	8	
Ctrl+Windows Key+9		*		*	9	
Ctrl+Windows Key+Backspace		*		*	Backspace	
Ctrl+Windows Key+C		*		*	C	
Ctrl+Windows Key+D		*		*	D	
Ctrl+Windows Key+E		*		*	E	
Ctrl+Windows Key+Enter		*		*	Enter	
Ctrl+Windows Key+F		*		*	F	
Ctrl+Windows Key+F14		*		*	F14	
Ctrl+Windows Key+F21		*		*	F21	
Ctrl+Windows Key+F22		*		*	F22	
Ctrl+Windows Key+F23		*		*	F23	
Ctrl+Windows Key+F24		*		*	F24	
Ctrl+Windows Key+F4		*		*	F4	
Ctrl+Windows Key+Left		*		*	Left	
Ctrl+Windows Key+M		*		*	M	
Ctrl+Windows Key+N		*		*	N	
Ctrl+Windows Key+O		*		*	O	
Ctrl+Windows Key+P		*		*	P	
Ctrl+Windows Key+Q		*		*	Q	
Ctrl+Windows Key+Right		*		*	Right	
Ctrl+Windows Key+S		*		*	S	
Ctrl+Windows Key+Space		*		*	Space	
Ctrl+Windows Key+V		*		*	V	
Shift+Windows Key+0			*	*	0	
Shift+Windows Key+1			*	*	1	
Shift+Windows Key+2			*	*	2	
Shift+Windows Key+3			*	*	3	
Shift+Windows Key+4			*	*	4	
Shift+Windows Key+5			*	*	5	
Shift+Windows Key+6			*	*	6	
Shift+Windows Key+7			*	*	7	
Shift+Windows Key+8			*	*	8	
Shift+Windows Key+9			*	*	9	
Shift+Windows Key+C			*	*	C	
Shift+Windows Key+Down			*	*	Down	
Shift+Windows Key+Enter			*	*	Enter	
Shift+Windows Key+F21			*	*	F21	
Shift+Windows Key+F22			*	*	F22	
Shift+Windows Key+Left			*	*	Left	
Shift+Windows Key+M			*	*	M	
Shift+Windows Key+P			*	*	P	
Shift+Windows Key+Right			*	*	Right	
Shift+Windows Key+S			*	*	S	
Shift+Windows Key+Space			*	*	Space	
Shift+Windows Key+T			*	*	T	
Shift+Windows Key+Up			*	*	Up	
Shift+Windows Key+V			*	*	V	
Shift+Windows Key+W			*	*	W	
Windows Key++				*	+	
Windows Key+,				*	,	
Windows Key+.				*	.	
Windows Key+0				*	0	
Windows Key+1				*	1	
Windows Key+2				*	2	
Windows Key+3				*	3	
Windows Key+4				*	4	
Windows Key+5				*	5	
Windows Key+6				*	6	
Windows Key+7				*	7	
Windows Key+8				*	8	
Windows Key+9				*	9	
Windows Key+;				*	;	
Windows Key+=				*	=	
Windows Key+A				*	A	
Windows Key+B				*	B	
Windows Key+Backspace				*	Backspace	
Windows Key+C				*	C	
Windows Key+D				*	D	
Windows Key+Down				*	Down	
Windows Key+E				*	E	
Windows Key+Enter				*	Enter	
Windows Key+F				*	F	
Windows Key+F1				*	F1	
Windows Key+F14				*	F14	
Windows Key+F15				*	F15	
Windows Key+F16				*	F16	
Windows Key+F21				*	F21	
Windows Key+F22				*	F22	
Windows Key+F24				*	F24	
Windows Key+G				*	G	
Windows Key+H				*	H	
Windows Key+Home				*	Home	
Windows Key+I				*	I	
Windows Key+J				*	J	
Windows Key+K				*	K	
Windows Key+L				*	L	
Windows Key+Left				*	Left	
Windows Key+M				*	M	
Windows Key+N				*	N	
Windows Key+O				*	O	
Windows Key+P				*	P	
Windows Key+Print Screen				*	Print Screen	
Windows Key+Q				*	Q	
Windows Key+R				*	R	
Windows Key+Right				*	Right	
Windows Key+S				*	S	
Windows Key+Space				*	Space	
Windows Key+T				*	T	
Windows Key+U				*	U	
Windows Key+Up				*	Up	
Windows Key+V				*	V	
Windows Key+W				*	W	
Windows Key+X				*	X	
Windows Key+Z				*	Z

**Comment by dreamforceinc** [comment]
Maybe use ALT+CTRL+DOWN hotkey ?

**Comment by fragtion** [comment]
4 keys just to minimize a window to tray? Nha fam

**Comment by sirloinofbeef** [comment]
>verify that this also works with Windows 11.

Working flawlessly. Thanks for all your work.

**Comment by Nechepso** [comment]
> > verify that this also works with Windows 11.
> 
> Working flawlessly. Thanks for all your work.

Unfortunately, not with all keyboards, it seems. I have a USB Microsoft Comfort Curve Keyboard plugged to my laptop. When I use the laptop's integrated keyboard, the <kbd>Win</kbd>+<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Down</kbd> shortcut works fine. However, when I use the USB keyboard, it doesn't.

My suspicion is that not all keyboards are able to send a 4-key press combination (not this specific one at least). See [this Stack Exchange entry](https://gaming.stackexchange.com/questions/6669/how-do-i-remove-the-limit-on-pc-keyboard-button-presses), for instance. I didn't try to capture key presses sent by my keyboard to confirm it was the actual problem, though.

> Maybe use ALT+CTRL+DOWN hotkey ? I'll check this tomorrow.

According to @sirloinofbeef's [dump](https://github.com/benbuck/rbtray/issues/62#issuecomment-939188596), this shortcut seems available, it's only using 3 keys and it's very close to the original (it just uses the <kbd>Ctrl</kbd> key instead of the <kbd>Win</kbd> key). Would it be possible to give it a try?

In any case, many thanks for maintaining this very useful software! 🙏

**Comment by dreamforceinc** [comment]
> According to @sirloinofbeef's [dump](https://github.com/benbuck/rbtray/issues/62#issuecomment-939188596), this shortcut seems available, it's only using 3 keys and it's very close to the original one (it just uses the Ctrl key instead of the Win key). Would it be possible to give it a try?

I checked it. Finally! :)
It (Alt+Ctrl+Down) works for me on Win10x64.

**Comment by benbuck** [comment]
Hi @dreamforceinc,

I just released version 4.14 which uses Ctrl-Alt-Down as the hotkey.

Take care,
Benbuck

**Comment by AZeed18** [comment]
I still got this problem

**Comment by guicbrito** [comment]
I can confirm this bug still exists on Windows 11. I'm using RBTray 4.14 on Windows 11 Education N edition (fresh install). The bug prevents RBTray from registering the hotkey and shows an error message every time it is launched. The error message is "Couldn't register hotkey". The right-click functionality works fine, but the hotkey does not. The bug is reproducible with the following steps: 
1. Install RBTray. 
2. Launch RBTray and see the error message. 
3. Try to use the hotkey and see that it does not work. 
4. Right-click the minimize button (or shift + right click) and see that it works. 
There is no way to change the hotkey or access any settings for RBTray. I wouldn't mind not using the hotkey, but the error prompt is unbearable.

**Comment by netdog2019** [comment]
I also confirm this bug still exists on Windows 11. I'm using RBTray 4.14

**Comment by pokemaster974** [comment]
Hello, I got this bug also on W10 (22H2)

**Comment by Greggles182** [comment]
Hi. Ctrl+Alt+Down Arrow turns my screen upside down. I am on latest Win 10 Pro. It also comes up with the error on latest release of this application on main branch. How to fix?

**Comment by multinomi** [comment]
> Hi. Ctrl+Alt+Down Arrow turns my screen upside down. I am on latest Win 10 Pro. It also comes up with the error on latest release of this application on main branch. How to fix?

Intel Iris Graphics Control Panel uses Ctrl+Alt+Down for screen rotation. You can disable the Hot Keys or change this shortcut to something else.
